export const elements = {
  summary: document.querySelector('#summary'),
  statusDot: document.querySelector('.status-dot'),
  runtimeStatus: document.querySelector('#runtime-status'),
  feedback: document.querySelector('#feedback'),
  viewButtons: [...document.querySelectorAll('[data-view]')],
  viewPanels: [...document.querySelectorAll('[data-view-panel]')],
  activePersonal: document.querySelector('#active-personal'),
  overviewMemoryCount: document.querySelector('#overview-memory-count'),
  overviewPendingCount: document.querySelector('#overview-pending-count'),
  overviewSpaceCount: document.querySelector('#overview-space-count'),
  overviewSubscriptionCount: document.querySelector('#overview-subscription-count'),
  recentList: document.querySelector('#recent-list'),
  lensList: document.querySelector('#lens-list'),
  factSection: document.querySelector('#facts-section'),
  factsList: document.querySelector('#facts-list'),
  timelineSection: document.querySelector('#timeline-section'),
  timelineList: document.querySelector('#timeline-list'),
  factCount: document.querySelector('#fact-count'),
  candidatesList: document.querySelector('#candidates-list'),
  candidateCount: document.querySelector('#candidate-count'),
  pendingNavCount: document.querySelector('#pending-nav-count'),
  spacesList: document.querySelector('#spaces-list'),
  subscriptionPersonal: document.querySelector('#subscription-personal'),
  subscriptionSpace: document.querySelector('#subscription-space')
};
